= mapping annotations

image:https://github.com/mihxil/mapping-annotations/actions/workflows/maven.yml/badge.svg?[Build Status,link=https://github.com/mihxil/mapping-annotations/actions/workflows/maven.yml]
image:https://codecov.io/gh/mihxil/mapping-annotations/branch/main/graph/badge.svg[codecov,link=https://codecov.io/gh/mihxil/mapping-annotations]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/org.meeuw.mapping/mapping-annotations.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/org/meeuw/mapping/]
image:https://www.javadoc.io/badge/org.meeuw.mapping/mapping-annotations.svg?color=blue[javadoc,link=https://www.javadoc.io/doc/org.meeuw.mapping/mapping-annotations]
image:https://img.shields.io/maven-central/v/org.meeuw.mapping/mapping-annotations.svg?label=Maven%20Central[Maven Central,link=https://central.sonatype.com/artifact/org.meeuw.mapping/mapping-annotations/overview]

Provides some annotation that can be added to field, indicating how they must be mapped

== Source annotations

The idea is that it in some mapping implementation it may be handy to annotate fields in the destination objects. Like so

[source, java]
----

import org.meeuw.mapping.annotations.Source;
..
class DestinationObject {

   @Source // This field is sourced by a field with the same name in souce objects
   String title;

   @Source(field = "_name") // This field is sourced by a field with the '_name' in source objects
   String name;

   @Source(field = "id", sourceClass=Identifiable.class) // This field is sourced by a field with the 'id', if the source fields is a 'Identifiable.
   Long id;
}
----

All fields annotated like so can be filled like this:
[source, java]
----
import org.meeuw.mapping.Mapper;
...

DestinationObject destination; SourceObject sourceObject;
Mapper.map(sourceObject, destination);;

----

So, this initial implementation:

- Makes no efforts _creating_ the objects. It just _fills_ them using reflection/direct field access

- So the object need be modifiable, but see link:#java_records[how it is supported for java records], immutability can be obtained by mapping to a builder.


== Sub fields
Sometimes not the value in a field itself is needed, but the value of field it _its_ value.

For that the 'path' atribute can be used.

[source, java]
----
@Source(field = "compoundId", path="id")
Long id;
----
which can also be deeper
[source, java]
----
@Source(path = {"a", "b"})
----

== Json sub fields

It is also possible to pick up values from a field containing json

[source, java]
----
class DestinationObject {
    ...
    @Source(field = "json", jsonPointer="/title") // This field is sourced by the json field 'title' within a field 'json' in the source object
    String title;
}
----
For more sophisticated cases it can also be done with jsonpath

[source, java]
----

    @Source(sourceClass = AggregatedMetadata.class, field = "payload", jsonPath = "['nisv.currentbroadcaster'][*]['currentbroadcaster.broadcaster']")
    protected List<EntityMetadata> broadcasters;
----

With
[source, java]
----
 public class EntityMetaData {
    @Source(jsonPointer = "/resolved_value", sourceClass = JsonNode.class)
    protected String name;
    ..
----
This also demonstrates that if the jsonPath/jsonPointer points to a JsonNode, that it can and will be implicitly converted further.


== Java records[[java_records]]

For now, java records (and probably other readonly structures) are supported if they have a (lombok generated) builder. Like so

[source, java]
----
package org.meeuw.mapping;

import org.meeuw.mapping.annotations.Source;

@lombok.Builder
public record DestinationRecord(
    @Source
    String title
) {
}
----

This is not tested for non-default lombok configurations. It assumes the builder to be named `-Builder`, it assumes the build-method in it to be `build()`. The `@Source` annotation are then found on the fields of the built class' fields.


[source, java]
----
@Test
public void toRecord() {
    SourceObject sourceObject = new SourceObject();
    sourceObject.setTitle("bla bla");
    var builder = DestinationRecord.builder();
    Mapper.map(sourceObject, builder);
    var r = builder.build();
    assertThat(r.title()).isEqualTo("bla bla");
}
----

So, you can map to the _builder_.

== Annotating the whole class

Defaults for all attributes of the `@Source` annotations can be added on class level
[source, java]
----
@Source(sourceClass = AggregatedMetadata.class, field = "payload")
public class Program {
----

For all fields in this class with `@Source` annotations the default value of the `sourceClass` and `field` attributes are not empty, but as specified on class level. In this way it is easy to map a bunch of field all from one source field (in this case `payload`), in this case for example by only specifing `@Source(jsonPointer='<something>')`


== Bean mapping generally

There are several bean mapping frameworks available, which may be used in stead or in conjuction with this

=== MapStruct

https://github.com/mapstruct/mapstruct[Mapstruct] is used compile time, to generate straightforward mappings code. It is
driven by 'mapper' interfaces which can be configured with annotations.
I didn't quite get it working yet, but I think it is mostly targeted at straightforward mappings where source and destination are very similar.


=== ModelMapper

https://modelmapper.org/[ModelMapper] seems more customizable, but still is basically targeted at mapping between very similar types. E.g. if you need to ignore fields those have to be skipped explicitly.

https://github.com/mihxil/modelmapper-json-source-annotation[This was however my first approach]. It is indeed possible to plugin the code of this project into ModelMapper. I'm  not sure how useful it is but, hopefully you could at least still profit from mapping between scalar types.

- Everything not completely simple seemed to be cumbersome
- Error message left to wish for

== Requirements
- java 17
- jackson2 is used for json parsing, slf4j2 for logging


== TODO

- Automatic mapping subtypes? (kinda done)
- Instantiating? (done with just default contructor)
- Implicit scalar-mapping (may be we can profit from spring conversion? from model mapper?)
